A searchengine endpoint to return the available values for a key in specific container
---
tags:
  - Available values for a key in specific container
parameters:
  - name: resource_table
    in: path
    type: string
    enum: ['image', 'project', 'screen', 'well', 'plate']
    required: true
  - name: container_name
    description: The container name
    in: query
    type: string
    required: true
  - name: key
    description: the resource attribute
    in: query
    type: string
    required: true
  - name: data_source
    in: query
    type: string
    required: false
    description: If it is provided, it will return the search results for a specific data source, otherwise it will return the results from all the data sources
  - name: csv
    description: a flag to return a CSV file which is created on the fly instead of JSON
    in: query
    type: boolean
    required: false

responses:
  200:
    description: A JSON contains the search results
    examples:
      results: []
